name: First Workfolw

on:
  push:
    branches:
      - main

jobs:
  ex-job:
    runs-on: ubuntu-latest

    steps:
      - name: welcome message
        run: echo "Welcome to our first GitHub Actions Workflow."
